# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: CodeQL3000Init@0
- task: CodeQL3000Finalize@0

# - task: CredScan@2
#   inputs:
#     toolMajorVersion: 'V2' 

# - task: ESLint@1
#   inputs:
#     Configuration: 'recommended'
#     TargetType: 'eslint'
#     ErrorLevel: 'warn'

# - task: Semmle@0
#   env:
#     SYSTEM_ACCESSTOKEN: $(System.AccessToken)
#   inputs:
#     sourceCodeDirectory: '$(Build.SourcesDirectory)'
#     language: 'tsandjs'
#     includeNodeModules: true
#     querySuite: 'Recommended'
#     timeout: '1800'
#     ram: '16384'
#     addProjectDirToScanningExclusionList: true

# - task: Semmle@1
#   inputs:
#     sourceCodeDirectory: '$(Build.SourcesDirectory)'
#     language: 'python'
#     querySuite: 'Recommended'
#     timeout: '1800'
#     ram: '16384'
#     addProjectDirToScanningExclusionList: true